USE clinicSystemDB;
SET FOREIGN_KEY_CHECKS=0;

DROP TABLE IF EXISTS clinic;
DROP TABLE IF EXISTS room;
DROP TABLE IF EXISTS appointment;
DROP TABLE IF EXISTS _user;
DROP TABLE IF EXISTS patient;
DROP TABLE IF EXISTS medical_staff;
DROP TABLE IF EXISTS doctor;
DROP TABLE IF EXISTS nurse;
DROP TABLE IF EXISTS examination;
DROP TABLE IF EXISTS bill;
DROP TABLE IF EXISTS medicine;
DROP TABLE IF EXISTS service;
DROP TABLE IF EXISTS work_at;
DROP TABLE IF EXISTS work_with;
DROP TABLE IF EXISTS patient_appointment;
DROP TABLE IF EXISTS medicine_in_clinic;
DROP TABLE IF EXISTS prescription;
DROP TABLE IF EXISTS clinic_hotline;
DROP TABLE IF EXISTS examination_allergy;
DROP TABLE IF EXISTS clinic_worktime;

SET FOREIGN_KEY_CHECKS=1;